### ISSUE TITLE
can Iframe use the add payment method in myaccount page?

### ISSUE THREAD

**Issue by JerixHub** [PayGate/PayWeb_WooCommerce#25]
I've implemented the paygate iframe to our website and it seems like the UI of "payment methods" in my account page is there, but doesn't seem to be working. can the Iframe type have a "add payment method" in myaccount page? I don't think I see the code in the plugin. also the plugin is already updated

**Comment by RBAtkins0n** [comment]
@JerixHub, would you be able to email support@paygate.co.za with access details?
We will then do our best t assist and commit any code changes if need be.
