### ISSUE TITLE
Session issue - v1.3.1

### ISSUE THREAD

**Issue by LirokData** [PayGate/PayWeb_WooCommerce#34]
I received a warning:

`PHP Warning:  session_start(): Cannot send session cache limiter - headers already sent (output started at ...\wp-includes\class.wp-styles.php:287)`

**Proposed change to line 66 of paygate.class.php v1.3.1 in WC_Gateway_PayGate:__construct():**
if ( session_status() === PHP_SESSION_NONE ) {
            session_start();
        }

**Comment by appinlet** [comment]
Noted with thanks.

**Comment by LirokData** [comment]
I was still having an issue in spite of that proposed change above but I got around the problem by hooking into wp_loaded and ensuring session is started there.

**Comment by appinlet** [comment]
We will have a look at the above to confirm. Session issues and output buffering can be affected by a number of local factors.

**Comment by LirokData** [comment]
You are right. Like I mentioned above this is what worked for me :

function check_session_started(){
		
	if ( session_status() === PHP_SESSION_NONE ) {
		session_start();
	}
}
add_action('wp_loaded', 'check_session_started', 10, 0 );

In my case something was causing wp-includes/class.wp-styles.php (which includes echo calls, hence output) to be called before Paygate plugin loads and thus causing the 'headers already sent' issue.

**Comment by appinlet** [comment]
This is most likely a space above an opening <?php tag in one of your plugins or your theme. We will still investigate and confirm though.

**Comment by appinlet** [comment]
This will be merged into next release.

**Comment by appinlet** [comment]
Fixed in #35

`if ( !headers_sent() && session_status() === PHP_SESSION_NONE ) {
        session_start();
    }`
