### ISSUE TITLE
PayWeb_WooCommerce Site Health Issues

### ISSUE THREAD

**Issue by TBart13** [PayGate/PayWeb_WooCommerce#37]
Hi Paygate Support,

We have been experiencing site performance and functionality issues, and we went through the effort of disabling all plugins and re-enabling each one until we found the culprit. When the PayWeb_WooCommerce plugin is enabled, the Health Check & Troubleshooting plugin reports a number of errors and warnings, including the following:
= An active PHP session was detected:
A PHP session was created by a session_start() function call. This interferes with REST API and loopback requests. The session should be closed by session_write_close() before making any HTTP requests.

= The REST API encountered an error:
The REST API is one way WordPress, and other applications, communicate with the server. One example is the block editor screen, which relies on this to display, and save, your posts and pages.

= Your site could not complete a loopback request:
Loopback requests are used to run scheduled events and are also used by the built-in editors for themes and plugins to verify code stability.
The loopback request to your site failed, this means features relying on them are not currently working as expected.
Error encountered: (0) cURL error 28: Operation timed out after 10001 milliseconds with 0 out of -1 bytes received

= The REST API request failed due to an error:
Error: cURL error 28: Operation timed out after 10001 milliseconds with 0 out of -1 bytes received (http_request_failed)

= Background updates may not be working properly:
Background updates ensure that WordPress can auto-update if a security update is released for the version you are currently using.

= Warning Could not confirm that the wp_version_check() filter is available.

Our site https://organica.co.za uses the Divi theme and builder, WordPress 5.5.1, WooCommerce  4.4.1 and PayWeb_WooCommerce plugin v1.4.0 together with a number of other plugins.

We urgently need to re-enable this plugin - please advise.

**Comment by appinlet** [comment]
Many thanks.
Have been in touch directly.

Resolved in #38
