### ISSUE TITLE
Unncessary Updater API requests

### ISSUE THREAD

**Issue by rahilwazir** [PayGate/PayWeb_WooCommerce#40]
The [`WP_GitHub_Updater_*`](https://github.com/PayGate/PayWeb_WooCommerce/blob/master/gateway-paygate.php#L83) class unnecssarily being called on the each admin pages. Which slows down the dashboard navigation.

This is also the case with https://github.com/PayGate/PaySubs_WooCommerce plugin.

See the screenshot from Query Monitor (took almost 5 seconds for both plugins):
![image](https://user-images.githubusercontent.com/1818941/107363162-955a7100-6afb-11eb-89d6-610db09ff4a4.png)

Sometimes it jumps to 10 seconds (depending on the connection speed).

It is recommended to run the updaters (or check for updates) only on **Dashboard - Updates** or **Plugins - Installed Plugins** screens.

**Comment by appinlet** [comment]
Thanks @rahilwazir,

We will be moving to woocommerce.org fairly soon and will be removing WP_GitHub_Updater_* completely.
