### ISSUE TITLE
Thank you for shopping with us. However, we were unable to initiate your payment. Please try again.

### ISSUE THREAD

**Issue by francoismarais** [PayGate/PayWeb_WooCommerce#43]
When testing in sandbox mode everything is fine, once it's switched over to the live website all that is returned is the following:
Thank you for shopping with us. However, we were unable to initiate your payment. Please try again.

**Comment by appinlet** [comment]
Hi @francoismarais, sorry to hear that.

Please contact the PayGate support team at support@paygate.co.za for further assistance on this matter.
