### ISSUE TITLE
PHP Notice:  Undefined index: pw3_e_scantopay 

### ISSUE THREAD

**Issue by Bruski** [PayGate/PayWeb_WooCommerce#48]
Hi Dev,

I am receiving alot of errors in my server log as below, please could we get this sorted on the next update?

PHP Notice:  Undefined index: pw3_e_scantopay in /wp-content/plugins/paygate-payweb-for-woocommerce/classes/WC_Gateway_PayGate.php on line 990

Thanks
Michael

**Comment by edotweb** [comment]
Hi Devs,

I can confirm above too. My server log is overflowing with these warning messages. We do not have Snap Scan / QR Code payment options enabled at all on the MAP or in the plugin. It also looks like the process might be causing the server to reach max_children: 20 on FPM/PHP 8.0.

PHP Warning:  Undefined array key "pw3_e_scantopay" in /wp-content/plugins/paygate-payweb-for-woocommerce/classes/WC_Gateway_PayGate.php on line 990
